from body_models.constants import Joint
from body_models.smpl.constants import SMPL_JOINTS


SMPLH_JOINT_NAMES = [
    "pelvis",
    "left_hip",
    "right_hip",
    "spine1",
    "left_knee",
    "right_knee",
    "spine2",
    "left_ankle",
    "right_ankle",
    "spine3",
    "left_foot",
    "right_foot",
    "neck",
    "left_collar",
    "right_collar",
    "head",
    "left_shoulder",
    "right_shoulder",
    "left_elbow",
    "right_elbow",
    "left_wrist",
    "right_wrist",
    "left_index1",
    "left_index2",
    "left_index3",
    "left_middle1",
    "left_middle2",
    "left_middle3",
    "left_pinky1",
    "left_pinky2",
    "left_pinky3",
    "left_ring1",
    "left_ring2",
    "left_ring3",
    "left_thumb1",
    "left_thumb2",
    "left_thumb3",
    "right_index1",
    "right_index2",
    "right_index3",
    "right_middle1",
    "right_middle2",
    "right_middle3",
    "right_pinky1",
    "right_pinky2",
    "right_pinky3",
    "right_ring1",
    "right_ring2",
    "right_ring3",
    "right_thumb1",
    "right_thumb2",
    "right_thumb3",
]

SMPLH_JOINTS = SMPL_JOINTS | {
    Joint.LEFT_THUMB_TIP: "left_thumb3",
    Joint.RIGHT_THUMB_TIP: "right_thumb3",
    Joint.LEFT_INDEX_TIP: "left_index3",
    Joint.RIGHT_INDEX_TIP: "right_index3",
    Joint.LEFT_MIDDLE_TIP: "left_middle3",
    Joint.RIGHT_MIDDLE_TIP: "right_middle3",
    Joint.LEFT_RING_TIP: "left_ring3",
    Joint.RIGHT_RING_TIP: "right_ring3",
    Joint.LEFT_PINKY_TIP: "left_pinky3",
    Joint.RIGHT_PINKY_TIP: "right_pinky3",
}

__all__ = ["SMPLH_JOINT_NAMES", "SMPLH_JOINTS"]
