from body_models.common.pose_assets import load_npz
from body_models.constants import Joint
from body_models.smpl.constants import SMPL_JOINTS


SMPLH_JOINT_NAMES = [
    "pelvis",
    "left_hip",
    "right_hip",
    "spine1",
    "left_knee",
    "right_knee",
    "spine2",
    "left_ankle",
    "right_ankle",
    "spine3",
    "left_foot",
    "right_foot",
    "neck",
    "left_collar",
    "right_collar",
    "head",
    "left_shoulder",
    "right_shoulder",
    "left_elbow",
    "right_elbow",
    "left_wrist",
    "right_wrist",
    "left_index1",
    "left_index2",
    "left_index3",
    "left_middle1",
    "left_middle2",
    "left_middle3",
    "left_pinky1",
    "left_pinky2",
    "left_pinky3",
    "left_ring1",
    "left_ring2",
    "left_ring3",
    "left_thumb1",
    "left_thumb2",
    "left_thumb3",
    "right_index1",
    "right_index2",
    "right_index3",
    "right_middle1",
    "right_middle2",
    "right_middle3",
    "right_pinky1",
    "right_pinky2",
    "right_pinky3",
    "right_ring1",
    "right_ring2",
    "right_ring3",
    "right_thumb1",
    "right_thumb2",
    "right_thumb3",
]

SMPLH_JOINTS = SMPL_JOINTS | {
    Joint.LEFT_THUMB_CMC: "left_thumb1",
    Joint.RIGHT_THUMB_CMC: "right_thumb1",
    Joint.LEFT_THUMB_MCP: "left_thumb2",
    Joint.RIGHT_THUMB_MCP: "right_thumb2",
    Joint.LEFT_THUMB_IP: "left_thumb3",
    Joint.RIGHT_THUMB_IP: "right_thumb3",
    Joint.LEFT_INDEX_MCP: "left_index1",
    Joint.RIGHT_INDEX_MCP: "right_index1",
    Joint.LEFT_INDEX_PIP: "left_index2",
    Joint.RIGHT_INDEX_PIP: "right_index2",
    Joint.LEFT_INDEX_DIP: "left_index3",
    Joint.RIGHT_INDEX_DIP: "right_index3",
    Joint.LEFT_MIDDLE_MCP: "left_middle1",
    Joint.RIGHT_MIDDLE_MCP: "right_middle1",
    Joint.LEFT_MIDDLE_PIP: "left_middle2",
    Joint.RIGHT_MIDDLE_PIP: "right_middle2",
    Joint.LEFT_MIDDLE_DIP: "left_middle3",
    Joint.RIGHT_MIDDLE_DIP: "right_middle3",
    Joint.LEFT_RING_MCP: "left_ring1",
    Joint.RIGHT_RING_MCP: "right_ring1",
    Joint.LEFT_RING_PIP: "left_ring2",
    Joint.RIGHT_RING_PIP: "right_ring2",
    Joint.LEFT_RING_DIP: "left_ring3",
    Joint.RIGHT_RING_DIP: "right_ring3",
    Joint.LEFT_PINKY_MCP: "left_pinky1",
    Joint.RIGHT_PINKY_MCP: "right_pinky1",
    Joint.LEFT_PINKY_PIP: "left_pinky2",
    Joint.RIGHT_PINKY_PIP: "right_pinky2",
    Joint.LEFT_PINKY_DIP: "left_pinky3",
    Joint.RIGHT_PINKY_DIP: "right_pinky3",
}

_POSES = load_npz("body_models.smplh")

SMPLH_BODY_PRESETS = _POSES["body"]
SMPLH_HAND_PRESETS = _POSES["hand"]

__all__ = ["SMPLH_JOINT_NAMES", "SMPLH_JOINTS", "SMPLH_BODY_PRESETS", "SMPLH_HAND_PRESETS"]
