from body_models.constants import Joint


ANNY_JOINTS = {
    Joint.LEFT_SHOULDER: "shoulder01.L",
    Joint.RIGHT_SHOULDER: "shoulder01.R",
    Joint.LEFT_ELBOW: "lowerarm01.L",
    Joint.RIGHT_ELBOW: "lowerarm01.R",
    Joint.LEFT_WRIST: "wrist.L",
    Joint.RIGHT_WRIST: "wrist.R",
    Joint.LEFT_THUMB_CMC: "finger1-1.L",
    Joint.RIGHT_THUMB_CMC: "finger1-1.R",
    Joint.LEFT_THUMB_MCP: "finger1-2.L",
    Joint.RIGHT_THUMB_MCP: "finger1-2.R",
    Joint.LEFT_THUMB_IP: "finger1-3.L",
    Joint.RIGHT_THUMB_IP: "finger1-3.R",
    Joint.LEFT_INDEX_MCP: "finger2-1.L",
    Joint.RIGHT_INDEX_MCP: "finger2-1.R",
    Joint.LEFT_INDEX_PIP: "finger2-2.L",
    Joint.RIGHT_INDEX_PIP: "finger2-2.R",
    Joint.LEFT_INDEX_DIP: "finger2-3.L",
    Joint.RIGHT_INDEX_DIP: "finger2-3.R",
    Joint.LEFT_MIDDLE_MCP: "finger3-1.L",
    Joint.RIGHT_MIDDLE_MCP: "finger3-1.R",
    Joint.LEFT_MIDDLE_PIP: "finger3-2.L",
    Joint.RIGHT_MIDDLE_PIP: "finger3-2.R",
    Joint.LEFT_MIDDLE_DIP: "finger3-3.L",
    Joint.RIGHT_MIDDLE_DIP: "finger3-3.R",
    Joint.LEFT_RING_MCP: "finger4-1.L",
    Joint.RIGHT_RING_MCP: "finger4-1.R",
    Joint.LEFT_RING_PIP: "finger4-2.L",
    Joint.RIGHT_RING_PIP: "finger4-2.R",
    Joint.LEFT_RING_DIP: "finger4-3.L",
    Joint.RIGHT_RING_DIP: "finger4-3.R",
    Joint.LEFT_PINKY_MCP: "finger5-1.L",
    Joint.RIGHT_PINKY_MCP: "finger5-1.R",
    Joint.LEFT_PINKY_PIP: "finger5-2.L",
    Joint.RIGHT_PINKY_PIP: "finger5-2.R",
    Joint.LEFT_PINKY_DIP: "finger5-3.L",
    Joint.RIGHT_PINKY_DIP: "finger5-3.R",
    Joint.LEFT_HIP: "upperleg01.L",
    Joint.RIGHT_HIP: "upperleg01.R",
    Joint.LEFT_KNEE: "lowerleg01.L",
    Joint.RIGHT_KNEE: "lowerleg01.R",
    Joint.LEFT_ANKLE: "foot.L",
    Joint.RIGHT_ANKLE: "foot.R",
    Joint.LEFT_FOOT: "toe2-1.L",
    Joint.RIGHT_FOOT: "toe2-1.R",
}


__all__ = ["ANNY_JOINTS"]
